# Use an official Node.js runtime as a parent image
FROM node:14-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the working directory
COPY . ./

# Install any needed packages specified in package.json
RUN npm install

# Bundle app source inside the Docker image
COPY . .

# Make port 9000 available to the world outside this container
EXPOSE 9000

# Define environment variable
ENV NODE_ENV=production

# Run the application
CMD ["npm", "start"]

